apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
spec:
  selector:
    matchLabels:
      app: mediawiki
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-services
spec:
  selector:
    app: mediawiki
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer



